# Generated by Django 5.0.7 on 2024-07-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100)),
                ('space_desc', models.TextField()),
                ('space_img', models.ImageField(upload_to='space')),
            ],
        ),
    ]
