# Generated by Django 5.0.7 on 2024-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocketGeeks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
